name: CI

on:
    push:
        branches: ["**"]
        paths-ignore:
            - "README.md"
            - "docs/**"
            - "*.md"
            - ".gitignore"
            - "LICENSE"
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                python-version: ["3.12.5"]
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: pip
                  cache-dependency-path: |
                      requirements.txt
                      dev-requirements.txt

            - name: Cache Ruff
              uses: actions/cache@v4
              with:
                  path: .ruff_cache
                  key: ruff-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
                  restore-keys: |
                      ruff-${{ runner.os }}-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Ruff lint
              run: ruff check .

            - name: Black format check
              run: black --check .

            - name: Run tests
              run: pytest -q
